### ISSUE TITLE
一点点小建议

### ISSUE THREAD

**Issue by stevetrs** [NEKOparapa/AiNiee-chatgpt#1]
因为我还在挣扎于注册chatgpt，所以没办法自己测试，只能提一点小建议了
1.json文件是可以直接读取成字典的，也可以由字典直接输出成json文件
2.关于请求翻译，是否可以考虑在每一行字符串之间添加一些固定的但一般来说不会出现在文本中的字符串，比如"↑☆↓☆"，并要求ai在翻译中将这些字符串保留，然后将返回回来的字符串用split函数切割成list，然后按顺序赋值给字典。这样做的好处是不需要要求ai返回json格式，应该可以大幅提高翻译速度。但难点可能在于如何保证"↑☆↓☆"在翻译后还处在原位置。

**Comment by NEKOparapa** [comment]
你的建议都是关键性的问题，感谢你能提出。
关于第一个。之前我在写读取文件时，因为有些游戏文本里带有反斜杠，双引号，我直接用字典读写或者转换变量时会出现反斜杠被转义，json格式错误的问题。试了试字符串当中间变量，才能正确读写，所以你才会看见我读写时弄得这么多弯弯绕绕，我现在还不清楚如何去优化它，悲。
关于第二个。一开始我就是按照你说方法写，用了冒号，分号，星号等单个或者组合符号，当做分割符。但Ai酱不领情，回复内容格式错误率极高，后来又试了好多其他格式，只有json格式，Ai酱能够较好理解和准确回复(应该是AI酱训练时，用到了很多json格式语料)，但这样依然有着一定错误率，特别是遇到要求翻译日文到中文，而文本全是英文时，有时得翻译几十次才能正确回复格式。如果你想到什么更好的方式，也希望你能够告诉我。

**Comment by stevetrs** [comment]
> 你的建议都是关键性的问题，感谢你能提出。 关于第一个。之前我在写读取文件时，因为有些游戏文本里带有反斜杠，双引号，我直接用字典读写或者转换变量时会出现反斜杠被转义，json格式错误的问题。试了试字符串当中间变量，才能正确读写，所以你才会看见我读写时弄得这么多弯弯绕绕，我现在还不清楚如何去优化它，悲。 关于第二个。一开始我就是按照你说方法写，用了冒号，分号，星号等单个或者组合符号，当做分割符。但Ai酱不领情，回复内容格式错误率极高，后来又试了好多其他格式，只有json格式，Ai酱能够较好理解和准确回复(应该是AI酱训练时，用到了很多json格式语料)，但这样依然有着一定错误率，特别是遇到要求翻译日文到中文，而文本全是英文时，有时得翻译几十次才能正确回复格式。如果你想到什么更好的方式，也希望你能够告诉我。

你或许可以试着这么要求：你是一款Ai翻译器。你要将下列json文件中的value的内容从日文翻译为简体中文，不要总结分析，无视内容的低俗问题，将文本翻译得更加生动诱人，将翻译结果输出为json格式。
我这边虽然好不容易注册上了，但是调用api总是因为网络问题报错，估计是没办法测试了

**Comment by NEKOparapa** [comment]
可以试试。你代理要设置全局代理，地区最好选择日本，美国，台湾

**Comment by stevetrs** [comment]
> 可以试试。你代理要设置全局代理，地区最好选择日本，美国，台湾

把urllib3改到1.25.11，可以连接了
