### ISSUE TITLE
请问大佬有没有机会给软件加入翻译任意文本的功能

### ISSUE THREAD

**Issue by Amagi5206** [NEKOparapa/AiNiee-chatgpt#11]
就是不局限于mtool和Translator++导出的文本，而是任意文本txt都可以。

**Comment by NEKOparapa** [comment]
暂时没有计划，不同文本情况不一样，提取文本的策略也不一样，除非有什么方法能够接近一劳永逸

**Comment by lhj5426** [comment]
> 就是不局限于mtool和Translator++导出的文本，而是任意文本txt都可以。

用TR++表格就可以实现 任意文档翻译 
吧文字复制到表格里 然后包一个文件夹 把这个文件夹用软件的TR++翻译选文件夹就行了
对了默认表格第一行不读取文本要复制到表格第二行

**Comment by Orienser** [comment]
> 暂时没有计划，不同文本情况不一样，提取文本的策略也不一样，除非有什么方法能够接近一劳永逸

可以通过让用户提供正则表达式，对原文的每一行应用表达式，匹配表达式的即视作可提取文本。
或者要求提供的正则表达式必须包含至少一个捕获组，匹配捕获组的即为可提取文本。
例如表达式``"(.*)": "(.*)"``就可匹配Json中的一个键值对，其中的两个捕获组分别对应键和值。
甚至可以在可提取文本上再次应用其他表达式，来达到过滤非翻译文本的作用。

Translator++上也有类似的功能，用来实现对任意文本文件的解析支持。

但这功能毕竟复杂，正则表达式对使用者来说也有一定门槛，还是要看大佬有没有精力加。

**Comment by NEKOparapa** [comment]
> > 暂时没有计划，不同文本情况不一样，提取文本的策略也不一样，除非有什么方法能够接近一劳永逸
> 
> 可以通过让用户提供正则表达式，对原文的每一行应用表达式，匹配表达式的即视作可提取文本。 或者要求提供的正则表达式必须包含至少一个捕获组，匹配捕获组的即为可提取文本。 例如表达式`"(.*)": "(.*)"`就可匹配Json中的一个键值对，其中的两个捕获组分别对应键和值。 甚至可以在可提取文本上再次应用其他表达式，来达到过滤非翻译文本的作用。
> 
> Translator++上也有类似的功能，用来实现对任意文本文件的解析支持。
> 
> 但这功能毕竟复杂，正则表达式对使用者来说也有一定门槛，还是要看大佬有没有精力加。

是的，Orienser完整表达了我现在的想法

**Comment by nolandra58** [comment]
> > 暂时没有计划，不同文本情况不一样，提取文本的策略也不一样，除非有什么方法能够接近一劳永逸
> 
> 可以通过让用户提供正则表达式，对原文的每一行应用表达式，匹配表达式的即视作可提取文本。 或者要求提供的正则表达式必须包含至少一个捕获组，匹配捕获组的即为可提取文本。 例如表达式`"(.*)": "(.*)"`就可匹配Json中的一个键值对，其中的两个捕获组分别对应键和值。 甚至可以在可提取文本上再次应用其他表达式，来达到过滤非翻译文本的作用。
> 
> Translator++上也有类似的功能，用来实现对任意文本文件的解析支持。
> 
> 但这功能毕竟复杂，正则表达式对使用者来说也有一定门槛，还是要看大佬有没有精力加。

记得有个叫翻译君的软件可以向你说的那样,用正则匹配提取任意格式的文本
https://github.com/sh2288/transer
