### ISSUE TITLE
大佬，readme.md有字写错啦&小建议

### ISSUE THREAD

**Issue by Abcuders** [NEKOparapa/AiNiee-chatgpt#12]
* 1.Python写成pythone啦
    > https://github.com/NEKOparapa/AiNiee-chatgpt/blob/main/README.md#L17-L17 
 * 2.小小小小建议
   > 大佬有时间可以美化一下readme.md，这样看上去会更舒服

**Comment by NEKOparapa** [comment]
谢谢提醒，有无好看的readme推荐

**Comment by Abcuders** [comment]
不晓得，如果可以的话，我可以写一个md出来，大概就和我仓库里的差不多
