### ISSUE TITLE
初始化依赖环境.cmd 这个文件可以去掉或者更改内容代码么

### ISSUE THREAD

**Issue by Abcuders** [NEKOparapa/AiNiee-chatgpt#13]
因为pip可以用requirements.txt来进行自动依赖安装,不需要一条一条执行命令,另外这个cmd 中使用pip 直接安装依赖可能会出现Fatal error in launcher:Unable to create process using pip 这个问题,应该改用python3 -m pip install xxx更好，我也会在我负责的README.md文件中增加这部分的新内容

**Comment by NEKOparapa** [comment]
挺好的，改

**Comment by Abcuders** [comment]
那这个cmd 就交给你整合到releases里了,我没在源码里看到这个cmd 就不动手改了

**Comment by NEKOparapa** [comment]
嗯
