### ISSUE TITLE
怎么继续翻译啊？开了自动备份但下次打开会卡死不动

### ISSUE THREAD

**Issue by CatCars** [NEKOparapa/AiNiee-chatgpt#18]
![1](https://github.com/NEKOparapa/AiNiee-chatgpt/assets/44657929/88ba8fbe-6882-40d0-a0d8-7548bf43c6c4)
选择Backup Folder内的ManualTransFile，开始翻译后就一直这个界面

**Comment by NEKOparapa** [comment]
你是用mtool项目继续翻译的么？以及提供一下出错的ManualTransFile文件

**Comment by NEKOparapa** [comment]
已修复
