### ISSUE TITLE
Translator++ 导入的时候都会卡住

### ISSUE THREAD

**Issue by Mr-small-2-six** [NEKOparapa/AiNiee-chatgpt#19]
Translator++ 导入的时候都会卡住
有没有办法直接翻译renpy文件呢

**Comment by NEKOparapa** [comment]
提取文本后，写个转化脚本，转化成Mtool的json格式，翻译完成后。再写个脚本，转化回去。

**Comment by Mr0KL** [comment]
> 方法1：导入时，把卡住的表格文件拿出来，后面再手动录入 方法2：提取文本后，写个转化脚本，转化成Mtool的json格式，翻译完成后。再写个脚本，转化回去。

是可以翻译了，找了几次chatgpt写脚本把翻译文件夹里rpy的文件弄成mtool的json格式了，也可以导入进去翻译了

非常感谢

只是编程小白，就算导入进去还是显示空白，看了多次renpy汉化教程，还是找不到方法，希望这里可以抛砖引玉让人可以翻译renpy的游戏了

非常感谢

**Comment by NEKOparapa** [comment]
目前已经修复因为整数型数据而导致的导入卡住问题
