### ISSUE TITLE
我想问一下为什么导入后代码缩成一行，我的文件是从apk文件直接解压的，运行日志我找不到了

### ISSUE THREAD

**Issue by 123dxx** [NEKOparapa/AiNiee-chatgpt#21]
[Desktop.zip](https://github.com/NEKOparapa/AiNiee-chatgpt/files/11828469/Desktop.zip)

**Comment by NEKOparapa** [comment]
你是用T++来翻译的吧，那你认真看一下2p的教程。至于json文件不自动换行，不影响正常使用。

**Comment by 123dxx** [comment]
可是我就是打不开
![QQ截图20230622121135](https://github.com/NEKOparapa/AiNiee-chatgpt/assets/134991057/26b41b43-10a2-43d7-8123-aa7ef00a1135)

**Comment by NEKOparapa** [comment]
不应该替换plugins.js，以及使用T++时，有时是需要排除bug的。T++会把文本占位符或者其他格式符号提取出来，要去看一下是不是和原文一致。

**Comment by 123dxx** [comment]
大佬把那些脚本换行后就都正常了
