### ISSUE TITLE
翻译时报错，提示 int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by adastra9257** [NEKOparapa/AiNiee-chatgpt#24]
OS：
Windows 10 LTSC 2019 (1809 17763.4499)

版本：
AiNiee-chatgpt 4.55

问题：
翻译过程中提示 int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
提示过后请求卡死，一直停留在“当前正在进行任务的子线程数： 1”，不再进行任务

备注：
使用代理账号翻译，且已经测试请求通过，可以翻译
该问题使用Mtools和Translator++均复现，参数均为默认参数（除了一次翻译10行+单线程，且单线程或多线程均出现此问题）

截图：
![problem](https://github.com/NEKOparapa/AiNiee-chatgpt/assets/50064227/758730a3-f92f-4b3b-ae7e-10d0dab76f5c)

**Comment by NEKOparapa** [comment]
你是使用哪个代理平台的？这个错误是经常出现，还是偶尔出现？代理平台通常不给多线程通信的。

**Comment by adastra9257** [comment]
我估计找到问题了😂 不是多线程的问题 我已经开单线程了
报错的原因是3194行涉及到一个int转换
`total_tokens_used = int(response["usage"]["total_tokens"])` 

我刚才试了下我那个代理的payload
`
{
	"choices": [
		{
			"finish_reason": "stop",
			"index": 0,
			"message": {
				"content": "Hello! How can I assist you today?",
				"role": "assistant"
			}
		}
	],
	"created": 1688141477,
	"id": "chatcmpl-Dn9crKhzfnfAURx4t9DZLw2c95zy",
	"model": "gpt-3.5-turbo",
	"object": "chat.completion",
	"usage": {
		"completion_tokens": null,
		"prompt_tokens": null,
		"total_tokens": null
	}
}
`
usage那边全是null 估计是这样才报exception了

**Comment by NEKOparapa** [comment]
牛的
