### ISSUE TITLE
错行检测的建议

### ISSUE THREAD

**Issue by wjh191** [NEKOparapa/AiNiee-chatgpt#29]
总结了一些日文翻译的规则：
含有「」的句子翻译后的结果必定有「」或者“”，
（）还是（）
『』的话是『』、“”、’‘三种
【】是【】
……。是……。
……是……
。！和？号原文有的话译文也会有，但译文有的话原文不一定有。
这些符号一般位于句末和句尾，有些游戏会把一句话分成数行，比如：
「这是
一句话」
所以最好是单个符号进行检测。

如果翻译的结果没有对应符号的话必定是错行。

**Comment by NEKOparapa** [comment]
AI翻译的稳定还是不够，之前按照我的经验，它会把比如“【小明】一会去吃烧烤吧”，翻译成”小明说一起去吃烧烤吧“，中间的特殊符号不见，但意思基本合得上。还有把日文省略号翻译成中文省略号，AI会根据自己的理解，修改句子中的文本符号。
欸，所以在符号检查中，我是统计全部符号错误的的行数，看看错误占比。而且符号检查也只作为辅助判断，不敢完全依赖它。
后面我会增加「」『』【】，增加了应该影响不大
