### ISSUE TITLE
无效的字符“<”

### ISSUE THREAD

**Issue by chencxt** [NEKOparapa/AiNiee-chatgpt#32]
不知道为什么，升级了最新版之后我每次使用gpt4系列模型的时候总会弹出同样的报错。
一开始我还以为自己的prompt没写好，但是当我把prompt删掉之后还是存在同样的问题。
我开始以为可能是json里面出现的这个字符，但是没有，也不知道是怎么回事。
去用了chatbox试了一下同样的api（gpt4模型下），发现可以正常对话，所以基本能排除是api和翻译文本的问题。
请大大求救。
报错详细：[1;33m线程ID:[0m  26828
[1;31mError:[0m api请求出现问题！错误信息如下
Error: invalid character '<' looking for beginning of value {"error":{"message":"invalid character '\u003c' looking for beginning of value","type":"one_api_error","param":"","code":"unmarshal_response_body_failed"}} 500 {'error': {'message': "invalid character '<' looking for beginning of value", 'type': 'one_api_error', 'param': '', 'code': 'unmarshal_response_body_failed'}} {'Date': 'Fri, 04 Aug 2023 09:44:00 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '155', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'}

[1;33mWarning:[0m api请求错误计次： 3

**Comment by chencxt** [comment]
![issue](https://github.com/chencxt/overload.github.io/blob/master/post-images/20230804181118.png)

**Comment by NEKOparapa** [comment]
这是国内平台代理中转的么

**Comment by chencxt** [comment]
> 这是国内平台代理中转的么

是的，用的国内的转发api

**Comment by NEKOparapa** [comment]
这个错误是偶尔出现么，还是一启动每个请求都这样。3.5系列模型能够正常使用么

**Comment by chencxt** [comment]
> 这个错误是偶尔出现么，还是一启动每个请求都这样。3.5系列模型能够正常使用么

每个版本都有这种报错，没每次请求都会产生报错。3.5系列模型均可以正常使用，但是gpt4系列每个都不行。

**Comment by NEKOparapa** [comment]
那应该是中转站的问题，可以联系一下站长反馈，或者去https://github.com/songquanpeng/one-api这个项目反馈

**Comment by NEKOparapa** [comment]
还有你可以尝试自己编写prompt时，把下面这部分内容去掉：：    ###
    The input content format is as follows:
    {"<text id>": "<Japanese text>"}
    ###
    The output content format is as follows:
    {"<text id>": "<translated text>"}

**Comment by chencxt** [comment]
> 还有你可以尝试自己编写prompt时，把下面这部分内容去掉，再去试一试gpt4模型，看看还出错不：： ### The input content format is as follows: {"": ""} ### The output content format is as follows: {"": ""}

依旧出错

**Comment by bai198611** [comment]
代理的问题
