### ISSUE TITLE
想請教關於OpenAI API付款的問題

### ISSUE THREAD

**Issue by Vetra7** [NEKOparapa/AiNiee-chatgpt#33]
作者您好，在得知有這個軟體後，想試著變成OpenAI的付費會員，
但沒有查詢到詳細的扣款方式，就我的理解，
假設我這個月只用了1刀的限額，下個月的帳單則是1刀，
而不是下個月收到120刀帳單(註冊時給的120刀限額)沒錯吧？
由於找不到其他人付款的經驗，因此來請教您，謝謝！

**Comment by NEKOparapa** [comment]
是的，变成付费会员需要绑定信用卡，你这个月用多少，下个月就扣多少。不过现在网络上，淘宝上有卖绑定黑卡的120刀账号是，通常在50rmb左右（以前是2rmb，可惜好日子过去了）；也有中转站，1rmb=1＄额度来算。

**Comment by Vetra7** [comment]
感謝回答，120刀帳戶就不冒著風險購買了，打算自己綁信用卡即可。
