### ISSUE TITLE
關於如何避免AI翻譯重複字詞導致迭代

### ISSUE THREAD

**Issue by Vetra7** [NEKOparapa/AiNiee-chatgpt#34]
![image](https://github.com/NEKOparapa/AiNiee-chatgpt/assets/141728489/dd60f67b-ed78-4003-8401-c0c122860812)
作者您好，想請問一下，這種情況是AI翻譯時自身出現問題？
發現有很多次只有啊啊啊  喔喔喔的翻譯結果 ，佔據不少數量，這是否也導致額外的token消費，有什麼方法可以避免嗎？
例如透過提示詞等等，謝謝。

**Comment by NEKOparapa** [comment]
这种回复会导致额外的消耗，提示词以前试过，没什么作用。

**Comment by NEKOparapa** [comment]
嗯嗯

**Comment by Vetra7** [comment]
另外一個問題是，每次發送請求會有提示詞，
目前是選擇3.5 turbo，想請教若是調整成3.5 turbo 16K，
對於節省4倍提示詞但提高token單價的計算，是否有比較節省消耗呢？

**Comment by NEKOparapa** [comment]
16k经过测试，回复慢，串行多，而且格式容易出错，并不推荐使用，目前好用的3.5模型就4k那两个，或者说4的模型

**Comment by Vetra7** [comment]
了解，感謝回覆
