### ISSUE TITLE
能像其他的ChatGPT开源项目哪样支持user access token调用的方式使用ChatGPT服务吗

### ISSUE THREAD

**Issue by oldtian123** [NEKOparapa/AiNiee-chatgpt#35]
如题，例如站内开源项目[https://github.com/Chanzhaoyu/chatgpt-web](url)这样，支持accesstoken的方式调用ChatGPT服务，没有api请求数量的限制，而且回答相对api要聪明。

**Comment by NEKOparapa** [comment]
1.当初构建程序框架时没考虑过网页，如果要添加网页基本要重构一遍大部分代码，出于时间与精力，就不考虑了。
2.推荐的工具中有使用各种网页接口来翻译的工具，是优秀的项目，可以去尝试使用
