### ISSUE TITLE
语气词报错

### ISSUE THREAD

**Issue by julienslink** [NEKOparapa/AiNiee-chatgpt#37]
英译中，在翻译如“ahhhh”，“hahaha”之类的文本时会出如下报错

[INFO] 当前发送的原文文本：
 {"0": "{i}AAAAAAAAH!!!{/i}"}
[1;34m[INFO][0m 当前等待AI回复的子线程数： 1
[1;34m[INFO][0m 当前正在进行任务的子线程数： 1

[1;33m线程ID:[0m  16260
[1;31mError:[0m api请求出现问题！错误信息如下
Error: 'str' object has no attribute 'get'

请问这种问题应该如何解决呢
谢谢大佬

**Comment by NEKOparapa** [comment]
提交一下你的原文文件

**Comment by NEKOparapa** [comment]
你在这个表格得加一行表头，具体内容参考rpg游戏导出的excel原文文件，第一行就是这个表头

**Comment by julienslink** [comment]
明白了，我这就去下个RPG游戏用translator++导出看一下看看是啥样的
多谢

**Comment by julienslink** [comment]
> 你在这个表格得加一行表头，具体内容参考rpg游戏导出的excel原文文件，第一行就是这个表头

Original Text	Initial	Machine translation	Better translation	Best translation
像这样的一行五个表头吗

**Comment by NEKOparapa** [comment]
嗯
