### ISSUE TITLE
希望有用户词典功能

### ISSUE THREAD

**Issue by OPPO9008** [NEKOparapa/AiNiee-chatgpt#4]
希望有用户词典功能，方便上下文一致体验  比如 
オマンコ 统一翻译为 小穴
れいな 统一为 玲奈
くるみ 统一为 胡桃

不同分段内GTP翻译的女主名不同，结合后就难崩了

**Comment by NEKOparapa** [comment]
将来会接入Translator++，你可以在这个软件上构建你的用户词典

**Comment by NEKOparapa** [comment]
已添加
