### ISSUE TITLE
大概以后就什么机会便宜又高质量的翻译了，openai不给120美金薅了

### ISSUE THREAD

**Issue by Mr-small-2-six** [NEKOparapa/AiNiee-chatgpt#40]
大概以后就什么机会便宜又高质量的翻译了，openai不给120美金薅了
开通了5美金后是可以直接用gpt4但是是跟着限制的，没有120美金薅羊毛了，还以为可以薅到gpt4羊毛
非常感谢作者，让我这几个月便宜的翻译了不少比机翻更高质量的游戏

**Comment by NEKOparapa** [comment]
没办法，等其他平台或者本地模型看看吧

**Comment by Mr-small-2-six** [comment]
本地模型我想尝试，想问下能不能兼容oobabooga-text-generation-webui的api自己试了几次，都不能调用
也尝试了google几次都找不到答案
OpenAI compatible API ready at: OPENAI_API_BASE=http://
这个网站放去官方那边吗？
