### ISSUE TITLE
关于格式转换问题

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [NEKOparapa/AiNiee-chatgpt#42]
大佬，能否支持两种格式互转啊
比如已经拿Mtool的跑了一遍，现在又想用Translator++了，能否将json转换为Translator++支持的格式啊，不想再去浪费key了

**Comment by NEKOparapa** [comment]
不行的，两个工具提出出来的文本不一样，就根本没法转换

**Comment by YaeSakuraQvQ** [comment]
可否以替换的方式进行处理呢，Translator++输出为csv，Mtool是json，根据文本进行替换(一边为翻译完的，另一边为导出的原始文本)
刚才让gpt帮我写了个python浅试了一下，发现大部分文本都能被替换的(包括带转义符的)，但是还有少量未能成功
可能是因为我知识浅薄水平有限吧...大佬有空看看试着做一下呗，感觉这个功能还是会挺有用的啊
