### ISSUE TITLE
希望可以支持其它格式的输入

### ISSUE THREAD

**Issue by TXT2GAM** [NEKOparapa/AiNiee-chatgpt#43]
或者降低对格式的要求，比如我有一份键值为空的json字典想要翻译
但是mtool项目必须要求键和键值相同

**Comment by NEKOparapa** [comment]
你可以转换成表格文件，然后用T++项目入口来翻译。现在不会考虑支持更多格式，除非有哪个好用的工具出现

**Comment by TXT2GAM** [comment]
明白了
