### ISSUE TITLE
关于port=443 error

### ISSUE THREAD

**Issue by TXT2GAM** [NEKOparapa/AiNiee-chatgpt#44]
`Error: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))`
最近出现的频率变高了，也看到群里有人在聊这个问题。我自己测试了一下，发现一个很奇怪的现象，这个error只会在即将翻译结束时出现。用同一组官方key双开ainiee测试，一个翻译进度卡条98%，频繁error；同一时间另一个文本量更大的游戏依然在满速翻译。直到第二个游戏翻译到95%左右也开始error。**也就是说这是和ip与网络环境无关的。**

**Comment by NEKOparapa** [comment]
翻译到特点进度，然后443是老问题了，建议是换贵点代理，或者找群友推荐一个代理
