### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3463 column 5 (char 190140)

### ISSUE THREAD

**Issue by jackson66631** [NEKOparapa/AiNiee-chatgpt#48]
![image](https://github.com/NEKOparapa/AiNiee-chatgpt/assets/61911811/36ec67b7-1130-4e9a-b4ef-784ab5b66868)
翻译备份文件夹的ManualTransFile.json就发生这个错误

**Comment by NEKOparapa** [comment]
你读取的文件可能已经损坏，格式错误了，看一下3463行  5列

**Comment by jackson66631** [comment]
感谢解答
