### ISSUE TITLE
目前是只能日语翻译成中文吗

### ISSUE THREAD

**Issue by yebing233** [NEKOparapa/AiNiee-chatgpt#5]
改了一下prompt里的英语
让他英译中，但是报错了
![QQ图片20230507235947](https://user-images.githubusercontent.com/74483828/236688764-5b4b49e7-2e7a-4fea-9feb-16c30da64b1c.jpg)

**Comment by NEKOparapa** [comment]
因为英文全部被过滤完了，一下就完成翻译了

**Comment by yebing233** [comment]
> 因为英文全部被过滤完了，一下就完成翻译了

群友帮忙解决了 感谢
