### ISSUE TITLE
希望能增加译后一键替换功能

### ISSUE THREAD

**Issue by TXT2GAM** [NEKOparapa/AiNiee-chatgpt#50]
最典型的就是日文引号「 」，gpt3.5有时会选择保留，有时会选择翻译为中文引号 “ ” ，希望添加“译后字典”功能实现一键替换。
还有其他各种情况，比如日语符号中的 ♡ ♪ ・在gbk编码中是没有的，因此在封包前还需要把这些符号替换成空字符或其他符号。

可能有人会说文本编辑器不就能一键替换吗。但是，仅仅是上面列举的就有好几种，还是希望能够自动化处理吧，就像翻译完能自动把繁中转简中，省去了用opencc t2s的步骤。

**Comment by NEKOparapa** [comment]
谢谢你的建议，译后字典可以改善翻译后一些错误内容，但考虑到使用的人不多，该功能更新会排得比较后

**Comment by TXT2GAM** [comment]
已解决
`        for key, value in dict.items():
            #如果value是字符串变量
            if isinstance(value, str):
                new_value = value.replace("⚡", "\n").replace("♫", "\r").replace("“","「").replace("”","」").replace("‘","『").replace("’","』")
                new_dict[key] = new_value`
