### ISSUE TITLE
提几个问题建议,希望大佬能加入完善

### ISSUE THREAD

**Issue by VFengChen** [NEKOparapa/AiNiee-chatgpt#51]
1.添加停止或暂停翻译,方便更换新KEY.目前一开始翻译,KEY用完了,就只能关闭软件重新开始,
2.目前API KEY界面管理功能有点乱有待完善:
(1)其实没必要专门弄两个API KEY输入框,建议把API KEY独立出来一个功能统一管理设置,勾选启用官方或者代理直接调用就可以
(2)加上类似提示字典标签页的添加新行的功能,并统计显示出目前KEY总数,最好能加上一键测试KEY和翻译过程,标记失效的KEY方便管理
(3) 测试请求目前只能识别第一个,不会调用后面的
(4) 建议取消KEY输入框的超文本格式,粘贴后把文本字体颜色等格式都带上了
(5) API KEY界面添加手动保存按钮,粘贴了几十个KEY不会自动保存,关闭软件后没了...崩溃
(6) 能不能加入实现失效KEY标识为红色,方便替换
3.目前项目输出文件夹会循环创建原文件夹和文件,好乱

**Comment by NEKOparapa** [comment]
谢谢你的建议，现在加入你建议的多key测试以及保存配置功能，有些功能需要重构界面与程序才，之后再进行添加
