### ISSUE TITLE
建议支持对1106以后的新模型直接调用json输出

### ISSUE THREAD

**Issue by liutehande** [NEKOparapa/AiNiee-chatgpt#52]
新模型可以通过设置type: "json_object"直接输出json格式

**Comment by liutehande** [comment]
# 改为新版调用
                    from openai import OpenAI
                    client = OpenAI(
                        base_url='xxx',
                        api_key='xxx'
                    )
                    response = client.chat.completions.create(
                        model= OpenAI_model,
                        messages = messages ,
                        temperature=temperature,
                        top_p = top_p,
                        presence_penalty=presence_penalty,
                        frequency_penalty=frequency_penalty,
                        response_format={"type": "json_object"}
                    )
                    
                    获取值的时候不能用原来的下标[]获取了，要改成.获取
                    
                    新版json约束测了20w文本，几乎百分百不会输出错误格式的json

**Comment by liutehande** [comment]
另prompt中必须要有‘json’字眼

**Comment by NEKOparapa** [comment]
嗯，因为openai新包改变了写法，我正在恢复功能中，jsonmode也会加的
