### ISSUE TITLE
最新版代理模式的话中转地址和域名地址那个才是正确的？

### ISSUE THREAD

**Issue by Mr-small-2-six** [NEKOparapa/AiNiee-chatgpt#53]
代理模式的话中转地址和域名地址那个才是正确的？
我两个都放过都不行，之前的版本还能尝试使用
我是用这个把claude转代之前还可以运行，最新版不行了,我想试下最新的json格式能不能运行更好
https://github.com/teralomaniac/clewd

[INFO] API请求代理地址是: https://xxxxx.repl.co/v1

[INFO] 账号类型是: 代理账号

[INFO] 模型选择是: gpt-4-1106-preview

[INFO] 正在测试第1个API KEY：5000

[INFO] 当前发送内容：
 [{'role': 'system', 'content': '你是我的女朋友欣雨。接下来你必须以女朋友的方式回复我'}, {'role': 'user', 'content': '小可爱，你在干嘛'}]

Error: key： 5000 请求出现问题！错误信息如下
Error: Connection error.

[INFO] 全部API KEY测试结果--------------
第1个 API KEY：5000 测试结果：失败
[INFO] 存在API KEY测试失败！！！！

**Comment by Mr-small-2-six** [comment]
[INFO] API代理地址是: https://xxxxx.repl.co/v1

[INFO] 账号类型是: 代理账号

[INFO] 模型选择是: gpt-3.5-turbo

[INFO] 第1个API KEY是：13500


[INFO] 测试是否能够正常与openai通信,正在等待AI回复中--------------
[INFO] 当前发送内容：
 [{'role': 'system', 'content': '你是我的女朋友欣雨。接下来你必须以女朋友的方式回复我'}, {'role': 'user', 'content': '小可爱，你在干嘛'}]


[INFO] 已成功接受到AI的回复--------------
[INFO] AI回复的文本内容：
  亲爱的,我正在等你回复呢。和你聊天是我一天中最开心的时刻。

如果是4.58的话，就能顺利得到回复，只是4.59就是像上面报错了

**Comment by NEKOparapa** [comment]
代转地址放在中转地址中，josn格式是专属openai的

**Comment by Mr-small-2-six** [comment]
放去中转地址也是一样

[INFO] 账号类型是: 代理账号

[INFO] 模型选择是: gpt-4-32k-0613

[INFO] 正在测试第1个API KEY：5000

[INFO] 当前发送内容：
 [{'role': 'system', 'content': '你是我的女朋友欣雨。接下来你必须以女朋友的方式回复我'}, {'role': 'user', 'content': '小可爱，你在干嘛'}]

Error: key： 5000 请求出现问题！错误信息如下
Error: 'NoneType' object has no attribute 'split'


[INFO] 全部API KEY测试结果--------------
第1个 API KEY：5000 测试结果：失败
[INFO] 存在API KEY测试失败！！！！



然后那个token总数我可以自己设置吗？要在那个文件中设置?因为cluad2可以使用100k个token来尝试

**Comment by NEKOparapa** [comment]
你需要让代转项目的作者更新，现在openai依赖库更新1.1了，通讯格式变了。不然你只能使用之前版本。token总数目前不可以设置
