### ISSUE TITLE
能否改为自动设置lines

### ISSUE THREAD

**Issue by stevetrs** [NEKOparapa/AiNiee-chatgpt#54]
有限制的是每次请求的总字数，如果自动计算单次请求的总字数，就不需要手动设置lines，并且每次请求都是最大lines
手动设置lines，如果遇到游戏文本特别长的情况，就很容易一直循环报错下去，没发现的话损失就大了

还有一个小问题，如果原文某一行只有标点符号，也是会被识别为格式错误的，好像只有mtool偶尔会有这种情况

**Comment by NEKOparapa** [comment]
现在还保留自选行数的功能，是因为有时降低行数可以减少ai翻译串行的问题，而且如果超了模型的输入tokens，接口就会返回错误，也不会扣钱，然后就会自动拆分。不过之后可以作为一个可选择功能来加入，实现难度不难，只是有点繁琐。

在程序里选择翻译日语文本时，会自动过滤不含中日字符的文本行，一般来说不会出现原文只有标点符号，如果再次出现了，可以提供一下原文文件，我复现一下，看看是什么问题

**Comment by stevetrs** [comment]
> 现在还保留自选行数的功能，是因为有时降低行数可以减少ai翻译串行的问题，而且如果超了模型的输入tokens，接口就会返回错误，也不会扣钱，然后就会自动拆分。不过之后可以作为一个可选择功能来加入，实现难度不难，只是有点繁琐。

提到这个问题主要是遇到了发送20行，但却只返回18行的问题，而且会不断重复

[Wrong position  440——460.zip](https://github.com/NEKOparapa/AiNiee-chatgpt/files/13459504/Wrong.position.440.460.zip)
比如说这种情况


> 在程序里选择翻译日语文本时，会自动过滤不含中日字符的文本行，一般来说不会出现原文只有标点符号，如果再次出现了，可以提供一下原文文件，我复现一下，看看是什么问题

原文件还真不太好找，遇到过几次，我记得好像都是“…”出的问题，也有可能是日语的省略号，反正就是省略号。这个在重复几次之后会进入迭代，然后就正常了

**Comment by NEKOparapa** [comment]
发送20行，但却只返回18行，这是AI的问题，以前就有了，发10行也会这样

**Comment by stevetrs** [comment]
> 发送20行，但却只返回18行，这是AI的问题，以前就有了，发10行也会这样

但是减少lines的确降低了出现的概率，感觉是和字数有关的。没降低lines时，花费了1刀多才2%的进度，降低了一下lines，全部翻完才话费3.多刀
