### ISSUE TITLE
4.59版本提示词有点问题

### ISSUE THREAD

**Issue by AmeowCAT** [NEKOparapa/AiNiee-chatgpt#55]
日翻中的时候 看了眼接口 实际发送的提示词是
Translate the text into English and output it in JSON format
虽然前面的提示加深了GPT的思想钢印 还是实现了日翻中 但是不太确定是否会有一点误差

**Comment by NEKOparapa** [comment]
非常感谢，确实存在这个问题，之前修改prompt时没注意。现在测试版已经修复
