### ISSUE TITLE
请问，有可能用 AiNiee 直接翻译普通的纯文本小说么？

### ISSUE THREAD

**Issue by kzcheng** [NEKOparapa/AiNiee-chatgpt#58]
萌新提问，有可能用 AiNiee 直接翻译普通的纯文本小说么？

我想要翻译一些纯文本的普通小说，日翻简中。我试着直接写一个 txt 然后把小说原文丢进去，再把文件改成 json。但是如果不是正确的 json 排版的话，会出错的样子。

另一个问题是，AiNiee 有办法使用 ChatGPT 的会员么？因为我已经有在充每个月的 ChatGPT Plus 了，所以如果能直接用我的聊天额度就好了。

但是因为 ChatGPT 本身没有 API 的样子，所以做不到……？

**Comment by NEKOparapa** [comment]
不行的，有其他专门翻译小说AI项目，你得自己去找找。plus会员仅可以使用网页的功能，接口的需要额外充值使用

**Comment by tisapphire** [comment]
可以试下，把txt切成mtool格式的json翻译，然后再把翻译好的json拼回txt
不过格式也许会出问题
