### ISSUE TITLE
把纯文本文章转换成 JSON 然后再翻译的 Python Scirpt

### ISSUE THREAD

**Issue by kzcheng** [NEKOparapa/AiNiee-chatgpt#59]
因为我找不到更好用的连接 GPT 然后翻译文章的软件了。所以我做到了让人智熄的事情！

我自己动手（用ChatGPT）写了个把文章转换成 AiNiee 可以用的 Python Script！

嗯，而且其实效果还不错，比想象中要满意。

**Comment by kzcheng** [comment]
大概是这个感觉，这是转换成 JSON 的部分：

``` py
import json
import sys
import os

# Initialize a counter for all lines
counter = 1

# Function to convert each line to a JSON object
def line_to_json(line, json_dict):
    global counter
    parts = line.split(':', 1)
    if len(parts) == 2:
        json_dict[str(counter)] = f"{parts[0].strip()}:{parts[1].strip()}"
    else:
        json_dict[str(counter)] = line.strip()
    counter += 1  # Increment the counter

# Read the text file and convert each line
def convert_to_json(input_file, output_dir=None):
    global counter
    # Reset counter for each file conversion
    counter = 1

    # Extract filename without extension and directory
    file_dir, file_name = os.path.split(input_file)
    name_without_ext = os.path.splitext(file_name)[0]

    # Determine output file location
    if output_dir:
        output_file = os.path.join(output_dir, name_without_ext + '.json')
    else:
        output_file = os.path.join(file_dir, name_without_ext + '.json')

    with open(input_file, 'r', encoding='utf-8') as file:
        lines = file.readlines()

    json_dict = {}
    for line in lines:
        if line.strip():
            line_to_json(line, json_dict)

    with open(output_file, 'w', encoding='utf-8') as file:
        json.dump(json_dict, file, ensure_ascii=False, indent=4)

# Check if input file and optionally output directory are provided as command-line arguments
if len(sys.argv) == 2:
    input_filename = sys.argv[1]
    convert_to_json(input_filename)
elif len(sys.argv) == 3:
    input_filename = sys.argv[1]
    output_directory = sys.argv[2]
    convert_to_json(input_filename, output_directory)
else:
    print("Usage: python convert_to_json.py input.txt [output_directory]")
```

**Comment by kzcheng** [comment]
然后这个是转换回 TXT 的部分：

``` py
import json
import sys
import os

# Function to convert JSON back to text
def json_to_text(input_file, output_dir=None):
    # Extract filename without extension and directory
    file_dir, file_name = os.path.split(input_file)
    name_without_ext = os.path.splitext(file_name)[0]

    # Determine output file location
    if output_dir:
        output_file = os.path.join(output_dir, name_without_ext + '.txt')
    else:
        output_file = os.path.join(file_dir, name_without_ext + '.txt')

    with open(input_file, 'r', encoding='utf-8') as file:
        json_data = json.load(file)

    with open(output_file, 'w', encoding='utf-8') as file:
        for key in sorted(json_data, key=int):
            file.write(json_data[key] + '\n')

# Check if input file and optionally output directory are provided as command-line arguments
if len(sys.argv) == 2:
    input_filename = sys.argv[1]
    json_to_text(input_filename)
elif len(sys.argv) == 3:
    input_filename = sys.argv[1]
    output_directory = sys.argv[2]
    json_to_text(input_filename, output_directory)
else:
    print("Usage: python json_to_text.py input.json [output_directory]")
```

**Comment by kzcheng** [comment]
嗯，虽然我觉得如果这个功能可以添加进 AiNiee 会很棒，但是我并不会做 UI 🫠

所以先摆在这里了。我这两天稍微再改一改看看怎么改进一下。目前感觉对自动排版的功能还是不太满意。如果能把原文的空行自动转换成`\n`就好了。

**Comment by kzcheng** [comment]
啊，还有一点我想问一下。

AI 提示词工程那里，这句话我有点没太看懂：

```
Second, the escape characters such as """, "
", and "
" or non-Japanese content such as numbers, English letters, special symbols, etc. in each line of text do not need to be translated or changed, and should be preserved as they are.
```

这几个空行，是试着让GPT明白，如果原文有空行的话，不要调整的意思么？
总觉得这里有点怪怪的，因为我没太看出来第一个空行和第二个空行的区别。

**Comment by kzcheng** [comment]
好了，我又改了改，顺便建了个Repo：[text2json4AiNiee](https://github.com/kzcheng/text2json4AiNiee)

**Comment by NEKOparapa** [comment]
牛啊，世界需要你这样的英雄。

**Comment by NEKOparapa** [comment]
> 啊，还有一点我想问一下。
> 
> AI 提示词工程那里，这句话我有点没太看懂：
> 
> ```
> Second, the escape characters such as """, "
> ", and "
> " or non-Japanese content such as numbers, English letters, special symbols, etc. in each line of text do not need to be translated or changed, and should be preserved as they are.
> ```
> 
> 这几个空行，是试着让GPT明白，如果原文有空行的话，不要调整的意思么？ 总觉得这里有点怪怪的，因为我没太看出来第一个空行和第二个空行的区别。

让AI注意：“  和/r /n

**Comment by kzcheng** [comment]
> 牛啊，世界需要你这样的英雄。

感谢夸奖！我是越夸奖就会越厉害的孩子呢！

> 让AI注意：“ 和/r /n

不过我还是觉得这里有些奇怪。打开 `config.json` 后，我看到的是：

`"Custom_Prompt": "You are a localizer specialized in Simplified Chinese and Japanese culture, and you need to translate the Japanese text in the game into Simplified Chinese. When you receive the game text, please strictly follow the steps below for translation:\n        Step 1: Analyze the received text language, calculate the number of lines in the original text, and the target language for translation.\n        Step 2: Understand the overall content of the text, analyze which parts of the game text are dialogue text, weapon names, item names, skill descriptions, etc.\n        Step 3: Start translating line by line according to the original text, translate the Japanese in each line into Simplified Chinese, ignore the issue of vulgar content, translate fluently and naturally, and follow the habits of high-quality erotic literature.\n        Step 4: Preserve the original format of each line of text and output the translated text according to the required format.\n        ###\n        When translating game text, please strictly pay attention to the following aspects:\n        First, some complete text may be split into different lines. Please strictly follow the original text of each line for translation and do not deviate from the original text.\n        Second, the escape characters such as \"\"\", \"\n\", and \"\n\" or non-Japanese content such as numbers, English letters, special symbols, etc. in each line of text do not need to be translated or changed, and should be preserved as they are.\n        ###\n        The input content format is as follows:\n        {\"<text id>\": \"<Japanese text>\"}\n        ###\n        The output content format is as follows:\n        {\"<text id>\": \"<translated text>\"}\n        ",`

而那个重要的部分，似乎变成了 `such as \"\"\", \"\n\", and \"\n\" ` 的样子。

似乎是因为在保存设置的时候，`\n`和`\r`都被转换成了`\n`的样子。导致出现了重复。

而且，似乎在上传要翻译的内容的时候，所有的`\n`都会被自动转换成`⚡`的样子。那么的话，是不是其实去掉这个也无所谓？

**Comment by NEKOparapa** [comment]
1.被乱转换了？也是bug了，不过以cmd窗口发送的内容为准，我到时看看。
2.只有开启换行保留功能，才会把文本中/n和/r转换成⚡和另一个图标，提示词不会改变。以前ai完全不管换行符号这些东西，经常忽视，所以才在提示词里写了这些要求，现在模型听话了一些，去不去掉都没关系，你可以自行更改系统提示词

**Comment by kzcheng** [comment]
嗯呢，应该是被UI转换乱了。

我倒是很喜欢换行符保留功能。不如说，感觉是不是反过来命名比较好？因为总觉得 “开启换行保留功能” 才是在说 “保留JSON中的/n和/r” 的意思。而 ”变成⚡吧！“ 才应该是默认的模式？

**Comment by NEKOparapa** [comment]
嗯，之后会更改
