### ISSUE TITLE
可以增加API域名设置功能吗

### ISSUE THREAD

**Issue by lhj5426** [NEKOparapa/AiNiee-chatgpt#6]
![image](https://user-images.githubusercontent.com/30548000/236796975-c059e23d-fccf-4dab-a818-d8fca936f5ef.png)

您好 

就是这种 API 域名的设置功能 因为现在可以买第三方服务的API 
速度也比 官方的免费API 快 而且 在国内的原因 买第三方的API 服务不用虚拟信用卡自己申请的方便
所以 可以考虑支持一下 自定义aPI 域名功能吗

**Comment by NEKOparapa** [comment]
可以添加，但需要等待两三个版本。不过现在很多10元120刀账号，5元120刀key，走国内代理，觉得不是很划算

**Comment by lhj5426** [comment]
> 可以添加，但需要等待两三个版本。不过现在很多10元120刀账号，5元120刀key，走国内_代理_，觉得不是很划算

 至少有的用吧  免费的 聊天行 但是翻译 确实太慢了 没有效率

**Comment by EXACG** [comment]
mark 也是用第三方的API 请求支持吧 走官方频率限制很麻烦

**Comment by NEKOparapa** [comment]
已添加

**Comment by lhj5426** [comment]
> 已添加
![image](https://github.com/NEKOparapa/AiNiee-chatgpt/assets/30548000/5d14b73e-51e2-4c24-b120-aee51413792d)

嗯测试可用 就是有时候会请求出错 用的  https://api.openai-sb.com
