### ISSUE TITLE
NEKO大大求加个联系方式吧！

### ISSUE THREAD

**Issue by kzcheng** [NEKOparapa/AiNiee-chatgpt#60]
NEKO大大好！

我想求加一个联系方式QQ，Discord，Email什么的都可以。

因为我想看看，我能不能也帮帮忙。虽然前端 UI 相关的东西我很不擅长。但是我大概可以用 Python 搞一搞你的万行 Pasta 玩玩看。

**Comment by NEKOparapa** [comment]
你可以加我建立的交流群。现在谷歌出了个gemin pro ，测试可用，而且要加一些新功能，我过段时间会对项目进行重构，暂时不用来闻屎山。不过，我考虑之后加一个提取mvmz项目游戏文本的功能，实现起来不难，就是繁琐，基本是看json文件里面的数据保存结构，然后写提取方法，然后尽量可以按照物品，人名，事件等等来分类放好文本，发给ai翻译，可以让翻译效果更好。如果你有意愿可以去尝试一下，你可以做成自己的项目，我来支持，或者封装成一个方法，我之后集成到项目里。

**Comment by kzcheng** [comment]
感谢！

我找到交流群了，Neko大大就是群主āáǎà对吧？

我在想的是，能不能让AiNiee翻译纯文本更加轻松好用一些。这两天我一直在用AiNiee翻译小说，感觉效果意外的非常好。

**Comment by NEKOparapa** [comment]
是的，其实翻译小说的ai，已经有人做项目了。

**Comment by NEKOparapa** [comment]
11111111，测试
