### ISSUE TITLE
翻译结果没有成功保存

### ISSUE THREAD

**Issue by stevetrs** [NEKOparapa/AiNiee-chatgpt#64]
翻译过程超级快，但是翻译完成后，结果中只有非常一小部分文本（都是一些很简单的单句和短语）被翻译了，包括备份文件，也几乎都是空白。
重复翻译一次，也是同样的结果
翻译的结果和原文件在下面的压缩文件里。
[翻译结果未保存.zip](https://github.com/NEKOparapa/AiNiee-chatgpt/files/13785925/default.zip)

**Comment by NEKOparapa** [comment]
好的，我看看

**Comment by stevetrs** [comment]
> 好的，我看看

因为这个文件特别大，保存要用很长时间，所以好像是因为我没有等保存完就关了……

**Comment by NEKOparapa** [comment]
q确实，把没能成功翻译独立出来，手动翻译或者半手动翻译，很好的建议，之后会考虑添加

**Comment by NEKOparapa** [comment]
你有兴趣加入后续的功能开发中么，之前我在幻想看见过你很多文章，看见你写过提取mzmv的提取程序，非常厉害。我希望后面软件能够加入自解密，自提取，自封回功能，让软件能够一键化，并且能够控制AI不同文本进行针对性翻译。
