### ISSUE TITLE
繁中自动转化简中问题

### ISSUE THREAD

**Issue by stevetrs** [NEKOparapa/AiNiee-chatgpt#67]
有一些情况需要特定部分文本为原文不能改变，但是通常这些文本是繁中，即使加在提示词典里，也会因为自动转化简中而改变
所以希望能加一个关闭自动转化简中的开关

**Comment by NEKOparapa** [comment]
好的，加一个简繁自动转换开关

**Comment by stevetrs** [comment]
> 你有兴趣加入软件后续的功能开发中么，之前我在幻想看见过你很多文章，用过你的软件，后面还看见你写过提取mzmv的提取程序，非常厉害。我希望后面软件能够加入自解密（只针对通用的加密），自提取（josn文件），自封回（json文件）功能，并且能够控制AI不同文本进行针对性翻译，让软件能够一键化。

纯业余人士，没系统学过编程，所以你让我自己写能写，但是看别人写的代码很难……包括我写的代码，别人也很难读

**Comment by NEKOparapa** [comment]
没关系的，你可以封装成一个函数，互相对接一下接口，或者你写成一个工具，发布成一个项目，之后我来支持也没问题，主要是为了解决受制于前置工具的枷锁，并且能够专门为AI翻译进行优化

**Comment by stevetrs** [comment]
> 没关系的，你可以封装成一个函数，互相对接一下接口，或者你写成一个工具，发布成一个项目，之后我来支持也没问题，主要是为了解决受制于前置工具的枷锁，并且能够专门为AI翻译进行优化

那或许可以试试？有群吗，或者你加我q：1763387630
等白天有时间可以聊聊
我先睡了XD
