### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by 1762011099** [NEKOparapa/AiNiee-chatgpt#71]
Error: 进行请求时出现问题！！！错误信息如下
Error: Connection error.
这个是我网络问题吗？测试的时候好好的，一翻译就出这个问题，关键是服务器还在跑翻译，本地一个都收不到
<img width="718" alt="PixPin_2024-01-18_21-54-13" src="https://github.com/NEKOparapa/AiNiee-chatgpt/assets/157030358/29bfc7e6-19a4-4c19-80c5-ba8c54ffc4d2">
<img width="960" alt="PixPin_2024-01-18_21-54-40" src="https://github.com/NEKOparapa/AiNiee-chatgpt/assets/157030358/7e41c7ae-94ad-4c1d-91bc-130b5ca25464">

**Comment by NEKOparapa** [comment]
是网络问题，你试试开个系统代理看看

**Comment by 1762011099** [comment]
开了代理也没用，虽然好点了，就前面几次还可以正常进行，后面就会出现连接问题。不知道是不是梯子问题，我一个人测试应该不准https://books.fishhawk.top/forum/65719bf16843e12bd3a4dc98,我是按照这个教程部署的,代理软件用的v2rayN

**Comment by NEKOparapa** [comment]
你可以换个云平台试试，国内autodl，也有教程，你找一下

**Comment by 1762011099** [comment]
通信没有问题了，提示slot unavailable.是什么原因啊

**Comment by NEKOparapa** [comment]
之前我也遇到过，把云平台关机重启就行了，反正是云平台的问题

**Comment by 1762011099** [comment]
谢谢，重启内核确实能解决问题，另外翻译的行数要设置很小，而且线程为1比较好，这就导致翻译的速度会很慢。
